name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# Define categories that will group PRs in the release notes
categories:
  - title: '### Added'
    labels:
      - 'feature'
      - 'enhancement'
      - 'added'
  - title: '### Changed'
    labels:
      - 'change'
      - 'changed'
  - title: '### Fixed'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '### Deprecated'
    labels:
      - 'deprecated'
  - title: '### Removed'
    labels:
      - 'removed'
  - title: '### Security'
    labels:
      - 'security'

# Include commits as well as PRs
include-commits: true
commit-template: '- $TITLE'

# Define how individual changes appear in the release notes
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

# How version numbers should be determined based on labels
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
  default: patch

# The actual template for the release notes - notice the double brackets around the date
template: |
  ## [$RESOLVED_VERSION] - [$RELEASE_DATE]

  $CHANGES

# Set the release date format to match your CHANGELOG.md
date-format: 'YYYY-MM-DD'