name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '### Added'
    labels:
      - 'feature'
      - 'enhancement'
      - 'added'
  - title: '### Changed'
    labels:
      - 'change'
      - 'changed'
  - title: '### Fixed'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '### Deprecated'
    labels:
      - 'deprecated'
  - title: '### Removed'
    labels:
      - 'removed'
  - title: '### Security'
    labels:
      - 'security'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## [$RESOLVED_VERSION] - [$RELEASE_DATE]

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION