title: ActionableMessages
description: PowerShell module for creating Actionable Messages
baseurl: "/ActionableMessages/docs"
url: "https://mynster9361.github.io"
theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge