title: ActionableMessages
description: PowerShell module for creating Actionable Messages with card elements
baseurl: "/ActionableMessages/docs"  # This matches your target-folder in the workflow
url: "https://Mynster9361.github.io"  # Replace with your actual GitHub username
theme: jekyll-theme-minimal

defaults:
  - scope:
      path: ""
    values:
      layout: default