name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'Public/**'
      - 'docs/**'
      - 'docs-site/**'
      - '.github/workflows/github-pages.yml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module -Name PlatyPS -Force

      - name: Generate docs
        shell: pwsh
        run: |
          Import-Module ./ActionableMessages.psd1 -Force
          $docsPath = "./docs-site/reference"

          # Ensure directory exists
          if (-not (Test-Path $docsPath)) {
            New-Item -ItemType Directory -Path $docsPath -Force
          }

          # Ensure parent directory exists for landing page
          $siteRoot = "./docs-site"
          if (-not (Test-Path $siteRoot)) {
            New-Item -ItemType Directory -Path $siteRoot -Force
          }

          # Generate reference docs
          New-MarkdownHelp -Module ActionableMessages -OutputFolder $docsPath -Force

          # Create reference index file
          @"
          # ActionableMessages PowerShell Module

          This is the reference documentation for the ActionableMessages PowerShell module.

          ## Available Commands

          $(Get-Command -Module ActionableMessages | ForEach-Object { "- [$($_.Name)]($($_.Name).md)" } | Sort-Object)
          "@ | Out-File -FilePath "$docsPath/index.md" -Encoding utf8

          # Create main landing page
          @"
          ---
          layout: default
          title: ActionableMessages
          ---

          # ActionableMessages PowerShell Module

          A PowerShell module for creating Microsoft Actionable Messages.

          ## Installation

          ```powershell
          Install-Module -Name ActionableMessages -Scope CurrentUser
          ```

          ## Quick Start

          ```powershell
          $card = New-AMCard -ThemeColor "#0078D7"
          Add-AMElement -InputObject $card -Element (New-AMTextBlock -Text "Hello, World!")
          $jsonCard = Export-AMCard -Card $card
          ```

          ## Documentation

          * [Command Reference](reference/index.md)
          * [GitHub Repository](https://github.com/Mynster9361/ActionableMessages)
          "@ | Out-File -FilePath "$siteRoot/index.md" -Encoding utf8


      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs-site
          target-folder: docs  # Deploy to /docs path to avoid conflicts
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}