name: Pester Tests

on:
  pull_request:
    branches: [ main, master, development ]
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'
      - '!.github/workflows/pester-tests.yml'

permissions:
  contents: read
  pull-requests: write
  issues: write
  security-events: write

jobs:
  test:
    name: Run Pester Tests
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PowerShell Module Cache
        id: cache-psmodules
        uses: actions/cache@v4.2.0
        with:
          path: |
            C:\Users\runneradmin\Documents\PowerShell\Modules
            C:\Program Files\PowerShell\Modules
            C:\Program Files\PowerShell\7\Modules
          key: ${{ runner.os }}-psmodules-${{ hashFiles('**/requirements.psd1') }}
          restore-keys: |
            ${{ runner.os }}-psmodules-

      - name: Install PowerShell Modules
        if: steps.cache-psmodules.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module -Name Pester -MinimumVersion 5.3.0 -Force -SkipPublisherCheck

      - name: Run Pester Tests
        id: pester
        shell: pwsh
        run: |
          # Create output paths
          $testResultsJson = "$env:GITHUB_WORKSPACE/test-results.json"
          $testResultsSarif = "$env:GITHUB_WORKSPACE/test-results.sarif"

          try {
            # Run tests
            Write-Host "Running Pester tests..."
            $result = Invoke-Pester -Path ${{ github.workspace }}\tests -PassThru

            # Save summary results as JSON
            $summary = @{
              TotalCount = $result.TotalCount
              PassedCount = $result.PassedCount
              FailedCount = $result.FailedCount
              SkippedCount = ($result.Skipped | Measure-Object).Count
              NotRunCount = ($result.NotRun | Measure-Object).Count
              Duration = $result.Duration.TotalSeconds
              FailedTests = @($result.Failed | ForEach-Object {
                @{
                  Name = $_.Name
                  Path = $_.Path
                  ErrorMessage = $_.ErrorRecord.Exception.Message
                }
              })
            }
            $summary | ConvertTo-Json -Depth 5 | Out-File $testResultsJson -Force

            # Create a simplified SARIF file without test details to avoid URI errors
            $sarifObj = @{
              '$schema' = "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json"
              version = "2.1.0"
              runs = @(
                @{
                  tool = @{
                    driver = @{
                      name = "Pester"
                      version = (Get-Module Pester).Version.ToString()
                      informationUri = "https://github.com/pester/Pester"
                      rules = @()
                    }
                  }
                  results = @()
                  invocations = @(
                    @{
                      executionSuccessful = ($result.FailedCount -eq 0)
                      toolExecutionNotifications = @(
                        @{
                          descriptor = @{
                            id = "PESTER1"
                          }
                          message = @{
                            text = "Pester executed $($result.TotalCount) tests. Passed: $($result.PassedCount), Failed: $($result.FailedCount), Skipped: $($result.SkippedCount)"
                          }
                          level = if ($result.FailedCount -gt 0) { "error" } else { "note" }
                        }
                      )
                    }
                  )
                }
              )
            }

            # Add only failed tests to the SARIF file to keep it simple
            $ruleIndex = 0
            foreach ($test in $result.Failed) {
              $ruleName = "Failed: $($test.Name)"
              $ruleId = "TEST$ruleIndex"

              # Get a safe string path
              $safeUri = "test-file-$ruleIndex.ps1"
              if ($test.Path -is [string]) {
                $relativePath = $test.Path.Replace($env:GITHUB_WORKSPACE, "").Replace("\", "/").TrimStart("/")
                if (-not [string]::IsNullOrEmpty($relativePath)) {
                  $safeUri = $relativePath
                }
              }

              # Debug info to see what's happening
              Write-Host "Adding test result #$ruleIndex. Name: $($test.Name), Path type: $($test.Path.GetType().Name)"

              # Add rule and result
              $sarifObj.runs[0].tool.driver.rules += @{
                id = $ruleId
                name = $ruleName
                shortDescription = @{
                  text = $test.Name
                }
              }

              $sarifObj.runs[0].results += @{
                ruleId = $ruleId
                message = @{
                  text = $test.ErrorRecord.Exception.Message
                }
                level = "error"
                locations = @(
                  @{
                    physicalLocation = @{
                      artifactLocation = @{
                        uri = $safeUri
                      }
                      region = @{
                        startLine = 1
                        startColumn = 1
                      }
                    }
                  }
                )
              }

              $ruleIndex++
            }

            # Save SARIF file
            $sarifObj | ConvertTo-Json -Depth 10 | Out-File $testResultsSarif -Force

            # Set outputs
            "total_count=$($result.TotalCount)" >> $env:GITHUB_OUTPUT
            "passed_count=$($result.PassedCount)" >> $env:GITHUB_OUTPUT
            "failed_count=$($result.FailedCount)" >> $env:GITHUB_OUTPUT
            "skipped_count=$($result.SkippedCount)" >> $env:GITHUB_OUTPUT

            if ($result.FailedCount -gt 0) {
              "result=failure" >> $env:GITHUB_OUTPUT
              exit 1
            } else {
              "result=success" >> $env:GITHUB_OUTPUT
            }
          }
          catch {
            Write-Error "Error running Pester tests: $_"
            "result=failure" >> $env:GITHUB_OUTPUT
            exit 1
          }



      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/test-results.sarif
          category: pester-tests

      - name: Check Test Results
        if: always()
        shell: pwsh
        run: |
          $result = "${{ steps.pester.outputs.result }}"
          if ($result -eq "failure") {
            throw "Tests failed"
          }